import type { NextPage } from 'next'
import Head from 'next/head'
import Footer from '../components/Footer'
import Typography from '@mui/material/Typography';
import Box from '@mui/material/Box';
import Container from '@mui/material/Container';
import CardComponent from '../components/Card'

const Home: NextPage = () => {
  return (
    <Container>
      <Head>
        <title>David Rodriguez FullStack</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box
        component="main"
        sx={{
          minHeight: "90vh",
          padding: "4rem 0",
          flex: 1,
          display: "flex",
          flexDirection: "column",
          justifyContent: "center",
          alignItems: "center"
        }}
      >
        <Typography variant="h4" align="center" gutterBottom>
          Bienvenidos a la prueba técnica para FullStack Developer
        </Typography>

        <Box
          sx={{
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            flexWrap: "wrap",
            maxWidth: "800px"
          }}>
          <CardComponent
            href="https://nextjs.org/docs"
            title="Documentation"
            description="Find in-depth information about Next.js features and API."
          />
          <CardComponent
            href="https://nextjs.org/learn"
            title="Learn"
            description="Learn about Next.js in an interactive course with quizzes!"
          />
          <CardComponent 
            href="https://github.com/vercel/next.js/tree/canary/examples"
            title="Examples"
            description="Discover and deploy boilerplate example Next.js projects."
          />
          <CardComponent
            href="/form"
            title="Formulario"
            description="Completar formulario"
            external={false}
          />
        </Box>
      </Box>
      <Footer />
    </Container >
  )
}

export default Home
