import "../styles/globals.css";
import type { AppProps } from "next/app";
import Head from "next/head";
import { ApolloClient, InMemoryCache, ApolloProvider } from "@apollo/client";
import Layout from "../components/Layout";
import { SnackbarProvider } from "notistack";

const baseURL = process.env.NEXT_PUBLIC_SERVICE_URL || "http://localhost:4000";

const client = new ApolloClient({
  uri: `${baseURL}/graphql`,
  cache: new InMemoryCache(),
  connectToDevTools: true,
});

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <ApolloProvider client={client}>
      <SnackbarProvider>
        <Layout>
          <Head>
            <title>David Rodriguez FullStack</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <Component {...pageProps} />
        </Layout>
      </SnackbarProvider>
    </ApolloProvider>
  );
}

export default MyApp;
